# Generated by Django 5.1.7 on 2025-03-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'click_history',
                'managed': False,
            },
        ),
    ]
