# Generated by Django 5.1.7 on 2025-04-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_searchhistory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchhistory',
            table='click_history',
        ),
    ]
