# Generated by Django 5.1.7 on 2025-04-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_searchhistory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchhistory',
            table='search_history',
        ),
    ]
