# Generated by Django 5.1.7 on 2025-04-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_preference_preferenceactivitycategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='preferenceactivitycategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='preferencecuisine',
            options={'managed': False},
        ),
    ]
