# Generated by Django 5.1.7 on 2025-04-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preference',
            table='preference',
        ),
        migrations.AlterModelTable(
            name='preferenceactivitycategory',
            table='preference_activity_category',
        ),
        migrations.AlterModelTable(
            name='preferencecuisine',
            table='preference_cuisine',
        ),
    ]
