# Generated by Django 5.1.7 on 2025-03-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('museum', 'Museum'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('guest_house', 'Guest House'), ('archaeological_site', 'Archaeological Site'), ('festival', 'Festival')], max_length=30)),
                ('entity_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite',
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
