# Generated by Django 5.1.7 on 2025-03-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='entity_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='entity_type',
            field=models.CharField(choices=[('activity', 'Activity'), ('museum', 'Museum'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('guest_house', 'Guest House'), ('archaeological_site', 'Archaeological Site'), ('festival', 'Festival')], max_length=30),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
