# Generated by Django 5.1.7 on 2025-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_activitycategory_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('suitable_for', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
    ]
