# Generated by Django 5.1.7 on 2025-04-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
    ]
