# Generated by Django 5.1.7 on 2025-04-06 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_alter_hotel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.destination'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='tourism.equipment'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Hotel name should contain only letters and numbers.', regex='^[A-Za-z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(message='Enter a valid website URL.')]),
        ),
    ]
