# Generated by Django 5.1.7 on 2025-04-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_hotel_destination_hotel_equipments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
    ]
