# Generated by Django 5.1.7 on 2025-04-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
    ]
