# Generated by Django 5.1.7 on 2025-04-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_hotel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hotel_equipments',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
    ]
