# Generated by Django 5.1.7 on 2025-04-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_hotelequipment_alter_hotel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelEquipment',
        ),
    ]
