# Generated by Django 5.1.7 on 2025-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_delete_hotelequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('museum', 'Museum'), ('festival', 'Festival'), ('guest_house', 'Guest House'), ('activity', 'Activity'), ('archaeological_site', 'Archaeological Site')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entity_images',
                'managed': False,
            },
        ),
    ]
