# Generated by Django 5.1.7 on 2025-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_entityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='entity_type',
            field=models.CharField(choices=[('guest_house', 'Guest House'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('museum', 'Museum'), ('festival', 'Festival'), ('activity', 'Activity'), ('archaeological_sites', 'Archaeological Sites'), ('circuit', 'Circuit')], max_length=50),
        ),
    ]
