export const FETCH_CIRCUIT_HISTORY_REQUEST = 'FETCH_CIRCUIT_HISTORY_REQUEST';
export const FETCH_CIRCUIT_HISTORY_SUCCESS = 'FETCH_CIRCUIT_HISTORY_SUCCESS';
export const FETCH_CIRCUIT_HISTORY_FAIL = 'FETCH_CIRCUIT_HISTORY_FAIL';

export const SAVE_CIRCUIT_HISTORY_REQUEST = 'SAVE_CIRCUIT_HISTORY_REQUEST';
export const SAVE_CIRCUIT_HISTORY_SUCCESS = 'SAVE_CIRCUIT_HISTORY_SUCCESS';
export const SAVE_CIRCUIT_HISTORY_FAIL = 'SAVE_CIRCUIT_HISTORY_FAIL';

export const CHECK_CIRCUIT_HISTORY_DUPLICATE_SUCCESS = 'CHECK_CIRCUIT_HISTORY_DUPLICATE_SUCCESS';
export const CHECK_CIRCUIT_HISTORY_DUPLICATE_FAIL = 'CHECK_CIRCUIT_HISTORY_DUPLICATE_FAIL';
export const CHECK_CIRCUIT_HISTORY_DUPLICATE_REQUEST = 'CHECK_CIRCUIT_HISTORY_DUPLICATE_REQUEST';






