export const FETCH_CIRCUIT_HISTORY_REQUEST = 'FETCH_CIRCUIT_HISTORY_REQUEST';
export const FETCH_CIRCUIT_HISTORY_SUCCESS = 'FETCH_CIRCUIT_HISTORY_SUCCESS';
export const FETCH_CIRCUIT_HISTORY_FAIL = 'FETCH_CIRCUIT_HISTORY_FAIL';