export const FETCH_GUIDES_REQUEST = 'FETCH_GUIDES_REQUEST';
export const FETCH_GUIDES_SUCCESS = 'FETCH_GUIDES_SUCCESS';
export const FETCH_GUIDES_FAIL = 'FETCH_GUIDES_FAIL';

export const FETCH_GUIDE_REQUEST = 'FETCH_GUIDE_REQUEST';
export const FETCH_GUIDE_SUCCESS = 'FETCH_GUIDE_SUCCESS';
export const FETCH_GUIDE_FAIL = 'FETCH_GUIDE_FAIL';

export const CREATE_GUIDE_REQUEST = 'CREATE_GUIDE_REQUEST';
export const CREATE_GUIDE_SUCCESS = 'CREATE_GUIDE_SUCCESS';
export const CREATE_GUIDE_FAIL = 'CREATE_GUIDE_FAIL';

export const UPDATE_GUIDE_REQUEST = 'UPDATE_GUIDE_REQUEST';
export const UPDATE_GUIDE_SUCCESS = 'UPDATE_GUIDE_SUCCESS';
export const UPDATE_GUIDE_FAIL = 'UPDATE_GUIDE_FAIL';

export const DELETE_GUIDE_REQUEST = 'DELETE_GUIDE_REQUEST';
export const DELETE_GUIDE_SUCCESS = 'DELETE_GUIDE_SUCCESS';
export const DELETE_GUIDE_FAIL = 'DELETE_GUIDE_FAIL';