# Generated by Django 5.1.7 on 2025-04-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='circuitschedule',
            options={'managed': False},
        ),
    ]
