# Generated by Django 5.1.7 on 2025-04-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_alter_circuit_options_alter_circuitschedule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'circuit_history',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='circuit',
            table='circuit',
        ),
        migrations.AlterModelTable(
            name='circuitschedule',
            table='circuit_schedule',
        ),
    ]
