# Generated by Django 5.1.7 on 2025-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_circuithistory_alter_circuit_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_gd', models.CharField(blank=True, max_length=100, null=True)),
                ('descatl', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_gui', models.CharField(max_length=255)),
                ('pre_guide', models.CharField(max_length=255)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_deb_activ', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guide',
                'managed': False,
            },
        ),
    ]
